version: '3.4'

services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: "dtreasury_development"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3007 -b '0.0.0.0'"
    depends_on:
      - database
    ports:
      - "3007:3007"
    volumes:
      - .:/myapp
      #- gem_cache:/usr/local/bundle/gems
    env_file: 
      .env
    environment:
      RAILS_ENV: development
      PORT: 3007

volumes:
  gem_cache:
  db_data: